### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by NeilOnasch0402** [otto-de/logsmith#204]
**What I did:**

Install WSL2
Start the Ubuntu shell

git clone logsmith
cd logsmith

./setup.sh
./package -w

**Output:**
... many successful INFO logs
`Collecting PyInstaller==4.0
  Downloading https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz (3.5MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\Python37\python.exe' 'c:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\users\root\Temp\tmpt2yi2w7s'
         cwd: C:\users\root\Temp\pip-install-4myezdck\PyInstaller
    Complete output (41 lines):
    Traceback (most recent call last):
      File "c:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
        main()
      File "c:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in run_setup
        self).run_setup(setup_script=setup_script)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 78, in <module>
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
        dist.parse_config_files()
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\dist.py", line 865, in parse_config_files
        self, self.command_options, ignore_option_errors=ignore_option_errors
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 174, in parse_configuration
        meta.parse()
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 496, in parse
        section_parser_method(section_options)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 470, in parse_section
        self[name] = value
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 278, in __setitem__
        value = parser(value)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 602, in _parse_version
        return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 412, in _parse_attr
        return expand.read_attr(attr_desc, package_dir, root_dir)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
        module = _load_spec(spec, module_name)
      File "C:\users\root\Temp\pip-build-env-uzxlu6cb\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\users\root\Temp\pip-install-4myezdck\PyInstaller\PyInstaller.py", line 16, in <module>
        from PyInstaller.__main__ import run
    ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\Python37\python.exe' 'c:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\users\root\Temp\tmpt2yi2w7s' Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 22.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

----

Similar output when I manually download the 6.1.0 release.

Is there another prerequisite step that I'm not aware of?  @mrolappe-o21

**Comment by NeilOnasch0402** [comment]
Well, seems like the cdrx/pyinstaller-windows docker image is just broken.

When built from windows itself via
`pip install -r requirements.txt
pyinstaller.exe .\logsmith.spec`

it does work. Might have to include QT6 Libraries into PATH to run the exe.
